version: '3.8'

services:
  redis:
    image: redis
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
      
  db:
    image: postgres
    volumes:
       - data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 5432:5432

  web:
    build: .
    image: geoattendance
    volumes:
      - .:/app
    network_mode: host
    # ports:
    #   - '192.168.1.4:8000:8000'
    env_file:
      - ./.env
    depends_on:
      - db
    
  nginx:
    build: ./nginx
    command: nginx -g 'daemon off;'
    ports:
      - "8084:80"
    depends_on: 
      - web
    volumes:
      - ./captive/static:/var/www/static
      - ./captive/media:/var/www/media

volumes:
  data:
    external: true